---
# tasks file for roles/k8scontrolplane

- name: Initialize the Kubernetes cluster using kubeadm
  become: yes
  command: kubeadm init --pod-network-cidr=10.0.0.0/16 --kubernetes-version={{ k8s_stripped_version }}
  run_once: True

- name: Setup kubeconfig for ansible user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/ansible/.kube
    - cp -i /etc/kubernetes/admin.conf /home/ansible/.kube/config
    - chown ansible:ansible /home/ansible/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl create -f https://docs.projectcalico.org/manifests/calico.yaml
  run_once: True

- name: Generate join command
  become: yes
  run_once: True
  command: kubeadm token create --print-join-command
  register: join_command
  tags: joincommand

- name: Copy join command to local file
  run_once: True
  local_action:
    module: copy
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "/home/averydev/dev/ansible/ansible/default/k8s/roles/k8scontrolplane/files/join_command.txt"
  tags: joincommand
