---
# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
# https://docs.docker.com/engine/install/ubuntu/#installation-methods
- hosts: all
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    become: true
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - ca-certificates
      - curl
      - gnupg

  - name: Move keyring
    become: true
    command: install -m 0755 -d /etc/apt/keyrings

  - name: Add an Apt signing key to a specific keyring file
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      keyring: /etc/apt/keyrings/docker.gpg

  - name: Add repo
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Run the equivalent of "apt-get update" as a separate step
    become: true
    apt:
      update_cache: yes

  - name: Install docker packages
    become: true
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  # - name: Add an apt signing key for Docker
  #   apt_key:
  #     url: https://download.docker.com/linux/ubuntu/gpg
  #     state: present

  # - name: Add apt repository for stable version
  #   apt_repository:
  #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  #     state: present

  # - name: Install docker and its dependecies
  #   apt: 
  #     name: "{{ packages }}"
  #     state: present
  #     update_cache: yes
  #   vars:
  #     packages:
  #     - docker-ce 
  #     - docker-ce-cli 
  #     - containerd.io
  #   notify:
  #     - docker status

  # - name: Add owner user to docker group
  #   user:
  #     name: owner
  #     group: docker

  # - name: Remove swapfile from /etc/fstab
  #   mount:
  #     name: "{{ item }}"
  #     fstype: swap
  #     state: absent
  #   with_items:
  #     - swap
  #     - none

  # - name: Disable swap
  #   command: swapoff -a
  #   when: ansible_swaptotal_mb > 0

  # - name: Add an apt signing key for Kubernetes
  #   apt_key:
  #     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  #     state: present

  # - name: Adding apt repository for Kubernetes
  #   apt_repository:
  #     repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
  #     state: present
  #     filename: kubernetes.list

  # - name: Install Kubernetes binaries
  #   apt: 
  #     name: "{{ packages }}"
  #     state: present
  #     update_cache: yes
  #   vars:
  #     packages:
  #       - kubelet 
  #       - kubeadm 
  #       - kubectl

  # - name: Configure node ip
  #   lineinfile:
  #     path: /etc/default/kubelet
  #     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
  #     create: yes

  # - name: Restart kubelet
  #   service:
  #     name: kubelet
  #     daemon_reload: yes
  #     state: restarted

  # # - name: Copy the join command to server location
  # #   copy: src=join-command dest=/tmp/join-command.sh mode=0777

  # # - name: Join the node to cluster
  # #   command: sh /tmp/join-command.sh

  # handlers:
  #   - name: docker status
  #     service: name=docker state=started